# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a36a95ca33c8d2d1acf396995d0e439b36948c8139d6c233c21b5a1e6749a9250b2544097d2b34e652cca9dfa7486b96b39365c265b6c9549dc31f047dd7130

test:
  secret_key_base: 9f25a302351c738f894c875997e7db15c43e57ec848db4d612cc68bc7611b8a9c8dae8bf59e441702bcd475df3ca66a8df25d7d420d8240558fc197bebe57a82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
